#! /bin/bash

# Deploy to self
sudo rm -r /srv/salt
sudo rm -r /srv/pillar
sudo cp -r /home/anton/Programming/SaltConfs /srv/salt &&
sudo mv /srv/salt/pillar /srv/pillar

# Deploy to argo
if ping argo.tuko.com -c 1 > /dev/null 2> /dev/null; then
  sudo tar -cvf SaltConfs.tar -C /home/anton/Programming SaltConfs > /dev/null
  scp SaltConfs.tar pirate@argo:/home/pirate/SaltConfs.tar
  sudo rm SaltConfs.tar
  ssh pirate@argo /home/pirate/push.sh
else
  echo "Argo: ping failed"
fi
