#! /bin/bash

# Deploy to self
sudo rm -r /srv/salt
sudo rm -r /srv/pillar
sudo cp -r /home/anton/Programming/SaltConfs /srv/salt &&
sudo mv /srv/salt/pillar /srv/pillar

# Deploy to argo
if ping blueridge.antonpaquin.me -c 1 > /dev/null 2> /dev/null; then
  sudo tar -cvf SaltConfs.tar -C /home/anton/Programming SaltConfs > /dev/null
  scp SaltConfs.tar blueridge:/home/pi/SaltConfs.tar
  sudo rm SaltConfs.tar
  ssh blueridge /home/pi/push.sh
else
  echo "BlueRidge: ping failed"
fi
