FROM resin/rpi-raspbian
LABEL maintainer "antonpaquin@gmail.com"

# Modify sources list
COPY apt-sources /etc/apt/sources.list

# apt-get update
RUN apt-get update

# stay running forever
ENTRYPOINT tail -f /dev/null
