#!/bin/sh

urxvt &
sxhkd &
feh --bg-scale /home/anton/.config/backgrounds/fehbg &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 &
bspc monitor -g 1920x1040+0+40 &

bspc config border_width 5 &
bspc config window_gap 10 &
bspc config pointer_action1 resize_corner &
